# Dependencies
highlighter:      rouge


# Permalinks
permalink:              /:categories/:title/
# relative_permalinks: true

# Setup
title:            Ravi Raja Merugu
tagline:          Python, Web, Data and Distrubuted Computing
description:      Diehard fan of Python and Opensource. Ex-Computational Biologist, A wanna be Scientist, Loves simulations and automations, swimmer. 
url:              http://rsquarelabs.com
release_id:       1231241242111
baseurl:          /

author:
  name:           'Ravi Raja Merugu'
  url:            https://twitter.com/rrmerugu
  email:          'rrmerugu@gmail.com'
  github:         'https://github.com/rrmerugu'
  twitter:        'https://twitter.com/rrmerugu'
  linkedin:       'https://www.linkedin.com/in/rrmerugu'


collections:
  - code
  - blog
  - talk
  - snippet




# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rrmerugu/rrmerugu.github.io

excerpt_separator: "<!--/excerpt-->"
