# Dependencies
highlighter:      rouge


gems:
  - jekyll-paginate
  - jekyll-feed


# Permalinks
permalink:              /blog/:categories/:title/
# relative_permalinks: true

# Setup
title:            Ravi Raja Merugu
tagline:          'A Computational Biologist who fell in love with Web Technologies'
description:      'A Biologist who fell in love with Codes and crazy things a code can do!'
url:              http://rsquarelabs.com
baseurl:          /

author:
  name:           'Ravi Raja Merugu'
  url:            https://twitter.com/rrmerugu
  email:          'rrmerugu@gmail.com'
  github:         'https://github.com/rrmerugu'
  twitter:        'https://twitter.com/rrmerugu'
  linkedin:       'https://www.linkedin.com/in/rrmerugu'



collections:
  - projects
  - blog


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rsquarelabs/rsquarelabs

excerpt_separator: "<!--/excerpt-->"
